name: Setup Common CI Prerequisites
description: Install Qt shared by CI workflows
runs:
  using: composite
  steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: 6.10.*
