add_library(TbUiLib STATIC)

target_sources(TbUiLib
  PRIVATE
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AboutDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Action.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionBuilder.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionContext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionExecutionContext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionInfo.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ActionMenu.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AnimationManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AppController.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AppInfoPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/AutoSizeTableRows.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/BitmapButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/BorderLine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/BorderPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CellView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ChoosePathTypeDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ClickableLabel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ClickableTitleBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CollapsibleTitledPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ColorButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ColorModel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ColorTable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ColorsPreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationContext.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationProfileEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationProfileListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationProfileManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationRun.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationRunner.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationTaskListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CompilationVariables.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Console.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ControlPointToolPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ContainerBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Contracts.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ControlListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CrashDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CrashReporter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CurrentGameIndicator.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/CyclingMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/DialogButtonLayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/DialogHeader.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/DrawShapeToolExtensionPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/DrawShapeToolExtensionPages.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/DrawShapeToolPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ElidedLabel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EmptyWidget.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EnableDisableTagCallback.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityBrowser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityBrowserView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityDefinitionFileChooser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityInspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityPropertyEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityPropertyGrid.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityPropertyItemDelegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityPropertyModel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/EntityPropertyTable.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FaceAttribsEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FaceInspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FileDialogDefaultDir.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FileEventFilter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FileLogger.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FixedWidthFont.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FlagsEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FlagsPopupEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FlashSelectionAnimation.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FlyModeHelper.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FormWithSectionsLayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/FourPaneMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameEngineDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameEngineProfileEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameEngineProfileListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameEngineProfileManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GameListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GamesPreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GetVersion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GlFunctions.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/GlQt.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ImageListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ImageUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/InfoPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/InputEvent.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Inspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/IssueBrowser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/IssueBrowserView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/KeySequenceEdit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/KeyboardPreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/KeyboardShortcutItemDelegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/KeyboardShortcutModel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/LaunchGameEngine.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/LaunchGameEngineDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/LayerEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/LayerListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/LimitedKeySequenceEdit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapDocumentActionCache.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapHookPreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapHookRunner.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapInspector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapView2D.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapView3D.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapViewActivationTracker.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapViewBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapViewBase.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapViewContainer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapViewToolBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapWindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MapWindowManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MaterialBrowser.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MaterialBrowserView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MaterialCollectionEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MiniToolBarLayout.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ModEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MousePreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MultiCompletionLineEdit.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/MultiPaneMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ObjExportDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/OnePaneMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/OutlinerModel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/OutlinerPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/PopupButton.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/PopupWindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/PreferenceDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/PreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QColorUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QKeySequenceUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QPathUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QPreferenceStore.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QPreferenceStoreDelegate.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QPreferenceStoreUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QStringUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QStyleUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QThreadUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/QWidgetUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/RecentDocumentListBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/RecentDocuments.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/RenderView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ReplaceMaterialDialog.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/RotateToolPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SweepToolPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ScaleToolPage.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SearchBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/KeyboardShortcutUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SignalDelayer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SliderWithLabel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartChoiceEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartColorEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartDefaultPropertyEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartFlagsEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartPropertyEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartPropertyEditorManager.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SmartWadEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SpinControl.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/Splitter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/StandardShortcut.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SwitchableMapViewContainer.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SwitchableTitledPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SyncHeightEventFilter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/SystemPaths.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TabBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TabBook.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TextOutputAdapter.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ThreePaneMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TitleBar.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TitledPanel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ToolBox.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ToolBoxConnector.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/TwoPaneMapView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/UvEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/UvView.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/UpdateConfig.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/UpdatePreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/UpdateVersion.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/VariableStoreModel.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ViewEditor.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ViewPreferencePane.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/ViewUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/WadUtils.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/WelcomeWindow.cpp
    ${CMAKE_CURRENT_SOURCE_DIR}/src/WidgetState.cpp

  PUBLIC FILE_SET headers TYPE HEADERS
    BASE_DIRS ${CMAKE_CURRENT_SOURCE_DIR}/include
    FILES
    # Cmake' automoc needs the header files to be added to the source files if they are in a separate folder
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/AboutDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/Action.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionBuilder.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionContext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionExecutionContext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionInfo.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ActionMenu.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/AnimationManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/AppController.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/AppInfoPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/AutoSizeTableRows.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/BitmapButton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/BorderLine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/BorderPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CellView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ChoosePathTypeDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ClickableLabel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ClickableTitleBar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CollapsibleTitledPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ColorButton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ColorModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ColorTable.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ColorsPreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationContext.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationProfileEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationProfileListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationProfileManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationRun.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationRunner.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationTaskListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CompilationVariables.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/Console.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ControlPointToolPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ContainerBar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/Contracts.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ControlListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CrashDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CrashReporter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CurrentGameIndicator.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/CyclingMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/DialogButtonLayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/DialogHeader.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/DrawShapeToolExtensionPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/DrawShapeToolExtensionPages.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/DrawShapeToolPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ElidedLabel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EmptyWidget.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EnableDisableTagCallback.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityBrowser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityBrowserView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityDefinitionFileChooser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityInspector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityPropertyEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityPropertyGrid.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityPropertyItemDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityPropertyModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/EntityPropertyTable.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FaceAttribsEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FaceInspector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FileDialogDefaultDir.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FileEventFilter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FileLogger.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FixedWidthFont.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FlagsEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FlagsPopupEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FlashSelectionAnimation.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FlyModeHelper.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FormWithSectionsLayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/FourPaneMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameEngineDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameEngineProfileEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameEngineProfileListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameEngineProfileManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GameListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GamesPreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GetVersion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GlFunctions.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/GlQt.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ImageListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ImageUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/InfoPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/InputEvent.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/Inspector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/IssueBrowser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/IssueBrowserView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/KeySequenceEdit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/KeyboardPreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/KeyboardShortcutItemDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/KeyboardShortcutModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/LaunchGameEngine.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/LaunchGameEngineDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/LayerEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/LayerListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/LimitedKeySequenceEdit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapDocumentActionCache.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapHookPreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapHookRunner.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapInspector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapView2D.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapView3D.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewActivationTracker.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewBar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewBase.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewContainer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewLayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapViewToolBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapWindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MapWindowManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MaterialBrowser.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MaterialBrowserView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MaterialCollectionEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MiniToolBarLayout.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ModEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MousePreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MultiCompletionLineEdit.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/MultiPaneMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ObjExportDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/OnePaneMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/OutlinerModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/OutlinerPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/PopupButton.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/PopupWindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/PreferenceDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/PreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QColorUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QKeySequenceUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QPathUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QPreferenceStore.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QPreferenceStoreDelegate.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QPreferenceStoreUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QStringUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QStyleUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QThreadUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QVecUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/QWidgetUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/RecentDocumentListBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/RecentDocuments.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/RenderView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ReplaceMaterialDialog.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/RotateToolPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SweepToolPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ScaleToolPage.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SearchBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/KeyboardShortcutUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SignalDelayer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SliderWithLabel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartChoiceEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartColorEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartDefaultPropertyEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartFlagsEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartPropertyEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartPropertyEditorManager.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SmartWadEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SpinControl.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/Splitter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/StandardShortcut.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SwitchableMapViewContainer.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SwitchableTitledPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SyncHeightEventFilter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/SystemPaths.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TabBar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TabBook.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TextOutputAdapter.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ThreePaneMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TitleBar.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TitledPanel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ToolBox.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ToolBoxConnector.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/TwoPaneMapView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/UvEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/UvView.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/UpdateConfig.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/UpdatePreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/UpdateVersion.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/VariableStoreModel.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ViewConstants.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ViewEditor.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ViewPreferencePane.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/ViewUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/WadUtils.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/WelcomeWindow.h
    ${CMAKE_CURRENT_SOURCE_DIR}/include/ui/WidgetState.h
)

target_link_libraries(TbUiLib
  PRIVATE
    CompilerConfig
    PrecompileQtHeaders
    PrecompileStdHeaders
    cpptrace::cpptrace
    ctre::ctre
    Qt6::Svg
    TbVersionLib
  PUBLIC
    KdLib
    Qt6::Network
    Qt6::OpenGL
    Qt6::OpenGLWidgets
    Qt6::Widgets
    TbAppLib
    TbBaseLib
    TbMdlLib
    TbPreferencesLib
    TbRenderLib
    UpdateLib
    VmLib
)

set_target_properties(TbUiLib PROPERTIES AUTOMOC TRUE)

if(APPLE)
    # Silence macOS OpenGL deprecation warnings
    target_compile_definitions(TbUiLib PRIVATE GL_SILENCE_DEPRECATION)
endif()

add_subdirectory(test)
add_subdirectory(test-utils)
