/*
 Copyright (C) 2025 Kristian Duske

 This file is part of TrenchBroom.

 TrenchBroom is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 TrenchBroom is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with TrenchBroom. If not, see <http://www.gnu.org/licenses/>.
 */

#include "mdl/EntityDefinitionUtils.h"

#include "mdl/EntityProperties.h"

namespace tb::mdl
{
namespace
{

auto getAllPropertyDefinitions(auto&& entityDefinitions)
{
  return entityDefinitions | std::views::transform([](auto&& entityDefinition) -> auto&& {
           return entityDefinition.propertyDefinitions;
         })
         | std::views::join;
}

bool hasAnyEntityLinkPropertyDefinition(
  const std::vector<mdl::EntityDefinition>& entityDefinitions)
{
  return std::ranges::any_of(
    getAllPropertyDefinitions(entityDefinitions), [](const auto& propertyDefinition) {
      return std::holds_alternative<mdl::PropertyValueTypes::TargetSource>(
               propertyDefinition.valueType)
             || std::holds_alternative<mdl::PropertyValueTypes::TargetDestination>(
               propertyDefinition.valueType);
    });
}

void addOrSetDefaultEntityLinkProperties(mdl::EntityDefinition& entityDefinition)
{
  static const auto keysAndValueTypes =
    std::vector<std::tuple<std::string, mdl::PropertyValueType, std::string>>{
      {mdl::EntityPropertyKeys::Target,
       mdl::PropertyValueTypes::TargetDestination{},
       "name of entity to trigger"},
      {mdl::EntityPropertyKeys::Killtarget,
       mdl::PropertyValueTypes::TargetDestination{},
       "name of entity to kill"},
      {mdl::EntityPropertyKeys::Targetname,
       mdl::PropertyValueTypes::TargetSource{},
       "target name for linking"}};

  for (const auto& [key, valueType, description] : keysAndValueTypes)
  {
    if (auto* propertyDefinition = mdl::getPropertyDefinition(entityDefinition, key))
    {
      propertyDefinition->valueType = valueType;
    }
    else
    {
      entityDefinition.propertyDefinitions.push_back(
        mdl::PropertyDefinition{key, valueType, description, "generated by TrenchBroom"});
    }
  }
}

} // namespace

void addOrSetDefaultEntityLinkProperties(
  std::vector<mdl::EntityDefinition>& entityDefinitions)
{
  if (!hasAnyEntityLinkPropertyDefinition(entityDefinitions))
  {
    for (auto& entityDefinition : entityDefinitions)
    {
      addOrSetDefaultEntityLinkProperties(entityDefinition);
    }
  }
}

} // namespace tb::mdl
