SET(LIB_GLEW_SOURCE_DIR "${LIB_SOURCE_DIR}/glew")
SET(LIB_GLEW_SOURCE "${LIB_GLEW_SOURCE_DIR}/glew.c")

# Suppress all warnings in 3rd party code
SET_SOURCE_FILES_PROPERTIES(${LIB_GLEW_SOURCE} PROPERTIES COMPILE_FLAGS "-w")

ADD_LIBRARY(glew ${LIB_GLEW_SOURCE} ${LIB_INCLUDE_DIR})

SET_TARGET_PROPERTIES(glew PROPERTIES COMPILE_DEFINITIONS "GLEW_STATIC")
