SET(LIB_GTEST_SOURCE_DIR "${LIB_SOURCE_DIR}/gtest")
SET(LIB_GTEST_SOURCE "${LIB_GTEST_SOURCE_DIR}/gtest-all.cc")
SET_SOURCE_FILES_PROPERTIES(${LIB_GTEST_SOURCE} PROPERTIES COMPILE_FLAGS "-w")

ADD_LIBRARY(gtest ${LIB_GTEST_SOURCE} ${LIB_INCLUDE_DIR})

