IF (COMPILER_IS_MSVC)
	SET(LIB_STACKWALKER_SOURCE_DIR "${LIB_SOURCE_DIR}/stackwalker")
	SET(LIB_STACKWALKER_INCLUDE_DIR "${LIB_INCLUDE_DIR}/stackwalker")
	SET(LIB_STACKWALKER_SOURCE 
		"${LIB_STACKWALKER_SOURCE_DIR}/StackWalker.cpp"
		"${LIB_STACKWALKER_INCLUDE_DIR}/StackWalker.h")

	INCLUDE_DIRECTORIES(${LIB_STACKWALKER_INCLUDE_DIR})
	ADD_LIBRARY(stackwalker ${LIB_STACKWALKER_SOURCE})
ENDIF()
