FILE(READ "${INPUT}" HELP_CONTENTS)
STRING(REGEX REPLACE "#SC\\('([^']+)'\\)" "<script>shortcut(\"\\1\");</script>" HELP_CONTENTS_TRANSLATED "${HELP_CONTENTS}")
FILE(WRITE "${OUTPUT}" "${HELP_CONTENTS_TRANSLATED}")