SET(TEST_SOURCE_DIR "${CMAKE_SOURCE_DIR}/test/src")

IF(NOT CMAKE_GENERATOR STREQUAL "Xcode")
	FILE(GLOB_RECURSE TEST_SOURCE
	    "${TEST_SOURCE_DIR}/*.h"
	    "${TEST_SOURCE_DIR}/*.cpp"
	)
ELSE()
	FILE(GLOB_RECURSE TEST_SOURCE
	    "${TEST_SOURCE_DIR}/*.h"
	    "${TEST_SOURCE_DIR}/*.cpp"
		"${COMMON_SOURCE_DIR}/*.h"
	    "${COMMON_SOURCE_DIR}/*.cpp"
	)
ENDIF()

IF(NOT CMAKE_GENERATOR STREQUAL "Xcode")
	ADD_EXECUTABLE(TrenchBroom-Test ${TEST_SOURCE} $<TARGET_OBJECTS:common>)
ELSE()
	ADD_EXECUTABLE(TrenchBroom-Test ${TEST_SOURCE})
ENDIF()

ADD_TARGET_PROPERTY(TrenchBroom-Test INCLUDE_DIRECTORIES "${TEST_SOURCE_DIR}")
TARGET_LINK_LIBRARIES(TrenchBroom-Test gtest gmock ${wxWidgets_LIBRARIES} ${FREETYPE_LIBRARIES} ${FREEIMAGE_LIBRARIES})

# Copy some Windows-specific resources
IF(WIN32)
	ADD_CUSTOM_COMMAND(TARGET TrenchBroom-Test POST_BUILD
		COMMAND ${CMAKE_COMMAND} -E copy_directory "${LIB_BIN_DIR}/win32" "$<TARGET_FILE_DIR:TrenchBroom-Test>"
	)
ENDIF()

ADD_CUSTOM_COMMAND(TARGET TrenchBroom-Test POST_BUILD
    COMMAND ${CMAKE_COMMAND} -E copy_directory "${CMAKE_SOURCE_DIR}/test/data" "$<TARGET_FILE_DIR:TrenchBroom-Test>/data"
)

SET_XCODE_ATTRIBUTES(TrenchBroom-Test)

