SET(VECMATH_INCLUDE_DIR ${CMAKE_SOURCE_DIR}/vecmath/include)

ADD_LIBRARY(vecmath INTERFACE)
TARGET_INCLUDE_DIRECTORIES(vecmath INTERFACE
	$<BUILD_INTERFACE:${VECMATH_INCLUDE_DIR}>
	$<INSTALL_INTERFACE:vecmath/include/vecmath>
)
# SET_XCODE_ATTRIBUTES(vecmath)

INCLUDE_DIRECTORIES(${VECMATH_INCLUDE_DIR})
