SET(VECMATH_SOURCE_DIR ${CMAKE_SOURCE_DIR}/vecmath/src)

ADD_LIBRARY(vecmath INTERFACE)
TARGET_INCLUDE_DIRECTORIES(vecmath INTERFACE
	$<BUILD_INTERFACE:${VECMATH_SOURCE_DIR}>
	$<INSTALL_INTERFACE:include/vecmath>
)
# SET_XCODE_ATTRIBUTES(vecmath)

INCLUDE_DIRECTORIES(${VECMATH_SOURCE_DIR})
