/*
 Copyright (C) 2025 Kristian Duske

 This file is part of TrenchBroom.

 TrenchBroom is free software: you can redistribute it and/or modify
 it under the terms of the GNU General Public License as published by
 the Free Software Foundation, either version 3 of the License, or
 (at your option) any later version.

 TrenchBroom is distributed in the hope that it will be useful,
 but WITHOUT ANY WARRANTY; without even the implied warranty of
 MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 GNU General Public License for more details.

 You should have received a copy of the GNU General Public License
 along with TrenchBroom. If not, see <http://www.gnu.org/licenses/>.
 */

#include "io/EntityDefinitionClassInfo.h"
#include "mdl/EntityDefinition.h"
#include "mdl/EntityDefinitionUtils.h"
#include "mdl/EntityProperties.h"
#include "mdl/PropertyDefinition.h"

#include "catch/CatchConfig.h"

#include <catch2/catch_test_macros.hpp>
#include <catch2/generators/catch_generators.hpp>

namespace tb::mdl
{

TEST_CASE("addOrSetDefaultEntityLinkProperties")
{
  using namespace EntityPropertyKeys;
  using namespace PropertyValueTypes;

  static const auto targetDefinition = PropertyDefinition{
    Target, LinkSource{}, "name of entity to trigger", "generated by TrenchBroom"};
  static const auto killtargetDefinition = PropertyDefinition{
    Killtarget, LinkSource{}, "name of entity to kill", "generated by TrenchBroom"};
  static const auto targetnameDefinition = PropertyDefinition{
    Targetname, LinkTarget{}, "target name for linking", "generated by TrenchBroom"};

  using T = std::tuple<std::vector<EntityDefinition>, std::vector<EntityDefinition>>;

  const auto [originalDefinitions, expectedDefinitions] = GENERATE(values<T>({
    {{}, {}},
    {{
       {"some_definition", {}, "", {}},
     },
     {
       {"some_definition",
        {},
        "",
        {
          targetDefinition,
          killtargetDefinition,
          targetnameDefinition,
        }},
     }},
    {{
       {"some_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, String{}, "", ""},
          {Killtarget, String{}, "", ""},
          {Targetname, String{}, "", ""},
        }},
     },
     {
       {"some_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, LinkSource{}, "", ""},
          {Killtarget, LinkSource{}, "", ""},
          {Targetname, LinkTarget{}, "", ""},
        }},
     }},
    {{
       {"some_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, LinkSource{}, "", ""},
        }},
       {"some_other_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, String{}, "", ""},
          {Killtarget, String{}, "", ""},
          {Targetname, String{}, "", ""},
        }},
     },
     {
       {"some_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, LinkSource{}, "", ""},
        }},
       {"some_other_definition",
        {},
        "",
        {
          {"some_key", String{}, "", ""},
          {Target, String{}, "", ""},
          {Killtarget, String{}, "", ""},
          {Targetname, String{}, "", ""},
        }},
     }},
  }));

  CAPTURE(originalDefinitions);

  auto definitions = originalDefinitions;
  addOrSetDefaultEntityLinkProperties(definitions);

  CHECK(definitions == expectedDefinitions);
}

} // namespace tb::mdl
